#!/usr/bin/env node
/**
 * Vendor the shared bridge inspect shell into a module repository.
 *
 * Why vendoring rather than an npm dependency: this repository is `private: true` and its packages
 * resolve each other with `file:` links, so no module could install it from a registry. Requiring a
 * cross-repository checkout during a Pages build would turn a missing sibling into a failed deploy
 * rather than a degraded one, and every module repository is meant to remain independently
 * buildable by anyone who forks it. So the files are copied, and a hash manifest travels with them.
 *
 * The manifest is what makes the copy safe. It is written here, from the canonical source, and the
 * consuming repository checks its files against it on every build. Editing a vendored file breaks
 * the hash; the only way to change shared code is to change it here and re-sync. Divergence is
 * therefore detectable rather than a matter of noticing.
 *
 *   node tools/sync_viewer_ui.mjs --to c:/Dev/manhattan-bridge-3d
 *   node tools/sync_viewer_ui.mjs --to c:/Dev/manhattan-bridge-3d --check
 *
 * --check reports what would change and exits non-zero if anything would, so it can gate CI here.
 */
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, posix, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(HERE, '..', 'packages', 'bridge-viewer-ui', 'src');
/** Where a module keeps its vendored copy. Relative to the module repository root. */
const TARGET_SUBDIR = join('viewer', 'shared');
const MANIFEST_NAME = 'VIEWER-UI.sha256';

function walk(dir, base = dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full, base));
    else out.push(posix.join(...relative(base, full).split(/[\\/]/)));
  }
  return out.sort();
}

const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');

/**
 * Hash the bytes as they will exist on disk in the module repository. Line endings are normalised
 * to LF before hashing because a Windows checkout and a Linux CI runner must agree; this repository
 * learned that lesson once already, when a control document hashed two different ways on two
 * machines and a provenance check failed for a reason that had nothing to do with provenance.
 */
function canonical(buf) {
  return Buffer.from(buf.toString('utf8').replace(/\r\n/g, '\n'), 'utf8');
}

function build() {
  const files = walk(SOURCE);
  const entries = files.map((rel) => {
    const bytes = canonical(readFileSync(join(SOURCE, rel)));
    return { path: rel, sha256: sha256(bytes), bytes };
  });
  return entries;
}

function manifestText(entries, version) {
  const lines = [
    '# Shared bridge inspect shell — vendored copy.',
    '#',
    '# Generated by digital-3d-shared-contracts/tools/sync_viewer_ui.mjs. Do not edit, and do not',
    '# edit the files it lists: scripts/check_viewer_sync.mjs fails the build when they diverge.',
    '# To change shared viewer code, change it in digital-3d-shared-contracts and re-sync.',
    '#',
    `# package: @d3d/bridge-viewer-ui@${version}`,
    `# files:   ${entries.length}`,
    '',
    ...entries.map((e) => `${e.sha256}  ${e.path}`),
    '',
  ];
  return lines.join('\n');
}

function main() {
  const args = process.argv.slice(2);
  const toIndex = args.indexOf('--to');
  if (toIndex === -1 || !args[toIndex + 1]) {
    console.error('usage: node tools/sync_viewer_ui.mjs --to <module-repo-root> [--check]');
    process.exit(2);
  }
  const repo = resolve(args[toIndex + 1]);
  const check = args.includes('--check');
  if (!existsSync(repo)) {
    console.error(`no such directory: ${repo}`);
    process.exit(2);
  }

  const version = JSON.parse(
    readFileSync(resolve(HERE, '..', 'packages', 'bridge-viewer-ui', 'package.json'), 'utf8'),
  ).version;

  const entries = build();
  const dest = join(repo, TARGET_SUBDIR);
  const changed = [];
  const removed = [];

  for (const entry of entries) {
    const target = join(dest, entry.path.split('/').join(sep()));
    const current = existsSync(target) ? canonical(readFileSync(target)) : null;
    if (!current || sha256(current) !== entry.sha256) changed.push(entry.path);
  }

  if (existsSync(dest)) {
    const known = new Set(entries.map((e) => e.path));
    for (const rel of walk(dest)) {
      if (rel !== MANIFEST_NAME && !known.has(rel)) removed.push(rel);
    }
  }

  const manifest = manifestText(entries, version);
  const manifestPath = join(dest, MANIFEST_NAME);
  const manifestStale =
    !existsSync(manifestPath) || readFileSync(manifestPath, 'utf8').replace(/\r\n/g, '\n') !== manifest;

  if (check) {
    if (changed.length === 0 && removed.length === 0 && !manifestStale) {
      console.log(`${repo}: vendored viewer is in sync (${entries.length} files)`);
      process.exit(0);
    }
    for (const p of changed) console.error(`  would update  ${p}`);
    for (const p of removed) console.error(`  would remove  ${p}`);
    if (manifestStale) console.error(`  would update  ${MANIFEST_NAME}`);
    console.error(`${repo}: vendored viewer is OUT OF SYNC`);
    process.exit(1);
  }

  mkdirSync(dest, { recursive: true });
  for (const entry of entries) {
    const target = join(dest, entry.path.split('/').join(sep()));
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, entry.bytes);
  }
  for (const rel of removed) rmSync(join(dest, rel.split('/').join(sep())), { force: true });
  writeFileSync(manifestPath, manifest);

  console.log(`${repo}: wrote ${entries.length} files to ${TARGET_SUBDIR}`);
  if (changed.length) console.log(`  updated: ${changed.length}`);
  if (removed.length) console.log(`  removed: ${removed.length}`);
}

function sep() {
  return process.platform === 'win32' ? '\\' : '/';
}

main();
